### ISSUE TITLE
FAST FAST FAST

### ISSUE THREAD

**Issue by ivanstepanovftw** [peerigon/JavaScript.js#1]
> JavaScript.js is really fast. Actually, 10x faster than C. It also works in the cloud.

GODLIKE trolling level

**Comment by moritzjacobs** [comment]
True, @jhnns is a GODLIKE troll!

**Comment by jhnns** [comment]
Thanks ❤️

**Comment by jhnns** [comment]
We will continue our efforts to make it even faster of course.

**Comment by moritzjacobs** [comment]
Looking forward to the reimplementation of the core in Rust/WASM.

**Comment by jhnns** [comment]
We just got it 10x faster (see commit). Now you only need to be a 1x developer because the other 9x is done by...

🚨 **JAVASCRIPT.JS** 🚨

**Comment by moritzjacobs** [comment]
GODLIKE!

Now all we need is a webpack loader...

**Comment by moritzjacobs** [comment]
Also @jhnns can you npm publish plz thx lol
